name: businet_models
description: Businet Base Models.
version: 0.9.1
homepage: https://businet.com

# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  hive: ^2.2.3
  http: ^0.13.5
  # flutter_nexabase:
  #   path: C://H/flutter_nexabase
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  mongo_dart: ^0.8.2
  # overlay_support: ^2.0.1
  # esc_pos_utils: ^1.1.0
  # esc_pos_printer: ^4.1.0
  path_provider: ^2.0.11
  image: ^4.0.15
  gbk_codec: ^0.4.0
  hex: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
