name: businet_models
description: Businet Base Models.
version: 0.9.1
homepage: https://businet.com

repository: https://github.com/Mopilani/businet_models

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  hive: ^2.2.3
  http: ^0.13.5
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  mongo_dart: ^0.9.1
  path_provider: ^2.0.11
  image: ^4.0.15
  gbk_codec: ^0.4.0
  hex: ^0.2.0
  realm_dart: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
